//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguibuddy.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linguibuddy.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your first 100 points.
        /// </summary>
        internal static string Achievement10Description {
            get {
                return ResourceManager.GetString("Achievement10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rookie Point Collector.
        /// </summary>
        internal static string Achievement10Name {
            get {
                return ResourceManager.GetString("Achievement10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 500 points.
        /// </summary>
        internal static string Achievement11Description {
            get {
                return ResourceManager.GetString("Achievement11Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprentice of Pointology.
        /// </summary>
        internal static string Achievement11Name {
            get {
                return ResourceManager.GetString("Achievement11Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 1000 points.
        /// </summary>
        internal static string Achievement12Description {
            get {
                return ResourceManager.GetString("Achievement12Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeyman of Points.
        /// </summary>
        internal static string Achievement12Name {
            get {
                return ResourceManager.GetString("Achievement12Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 2500 points.
        /// </summary>
        internal static string Achievement13Description {
            get {
                return ResourceManager.GetString("Achievement13Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasoned Point Hunter.
        /// </summary>
        internal static string Achievement13Name {
            get {
                return ResourceManager.GetString("Achievement13Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 5000 points.
        /// </summary>
        internal static string Achievement14Description {
            get {
                return ResourceManager.GetString("Achievement14Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointaholic.
        /// </summary>
        internal static string Achievement14Name {
            get {
                return ResourceManager.GetString("Achievement14Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 10000 points.
        /// </summary>
        internal static string Achievement15Description {
            get {
                return ResourceManager.GetString("Achievement15Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandmaster of Applied Pointology.
        /// </summary>
        internal static string Achievement15Name {
            get {
                return ResourceManager.GetString("Achievement15Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everyday for 3 days.
        /// </summary>
        internal static string Achievement20Description {
            get {
                return ResourceManager.GetString("Achievement20Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Steps.
        /// </summary>
        internal static string Achievement20Name {
            get {
                return ResourceManager.GetString("Achievement20Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everyday for 7 days.
        /// </summary>
        internal static string Achievement21Description {
            get {
                return ResourceManager.GetString("Achievement21Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Week with No Excuses.
        /// </summary>
        internal static string Achievement21Name {
            get {
                return ResourceManager.GetString("Achievement21Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everyday for 14 days.
        /// </summary>
        internal static string Achievement22Description {
            get {
                return ResourceManager.GetString("Achievement22Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit in the Making.
        /// </summary>
        internal static string Achievement22Name {
            get {
                return ResourceManager.GetString("Achievement22Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everyday for 30 days.
        /// </summary>
        internal static string Achievement23Description {
            get {
                return ResourceManager.GetString("Achievement23Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve got the Rhythm.
        /// </summary>
        internal static string Achievement23Name {
            get {
                return ResourceManager.GetString("Achievement23Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to: {0}.
        /// </summary>
        internal static string AddedToCollectionMessage {
            get {
                return ResourceManager.GetString("AddedToCollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to listen.
        /// </summary>
        internal static string AudioClick {
            get {
                return ResourceManager.GetString("AudioClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio error.
        /// </summary>
        internal static string AudioError {
            get {
                return ResourceManager.GetString("AudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the word to the sound.
        /// </summary>
        internal static string AudioQuizDesc {
            get {
                return ResourceManager.GetString("AudioQuizDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize audio.
        /// </summary>
        internal static string AudioRecognize {
            get {
                return ResourceManager.GetString("AudioRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        internal static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a collection.
        /// </summary>
        internal static string ChooseCollection {
            get {
                return ResourceManager.GetString("ChooseCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is empty.
        /// </summary>
        internal static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome! It&apos;s the correct answer..
        /// </summary>
        internal static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers:.
        /// </summary>
        internal static string CorrectAnswersCount {
            get {
                return ResourceManager.GetString("CorrectAnswersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFEAT.
        /// </summary>
        internal static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an English word.
        /// </summary>
        internal static string DictionarySearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("DictionarySearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit collection.
        /// </summary>
        internal static string EditCollection {
            get {
                return ResourceManager.GetString("EditCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Correct:.
        /// </summary>
        internal static string ErrorCorrect {
            get {
                return ResourceManager.GetString("ErrorCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the question.
        /// </summary>
        internal static string FailedLoadQuestion {
            get {
                return ResourceManager.GetString("FailedLoadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve word.
        /// </summary>
        internal static string FailedWordRetrieval {
            get {
                return ResourceManager.GetString("FailedWordRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards.
        /// </summary>
        internal static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flashcards.
        /// </summary>
        internal static string FlashcardsCount {
            get {
                return ResourceManager.GetString("FlashcardsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangman.
        /// </summary>
        internal static string Hangman {
            get {
                return ResourceManager.GetString("Hangman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangman game.
        /// </summary>
        internal static string HangmanDesc {
            get {
                return ResourceManager.GetString("HangmanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        internal static string IDontKnow {
            get {
                return ResourceManager.GetString("IDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know.
        /// </summary>
        internal static string IKnow {
            get {
                return ResourceManager.GetString("IKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you see in the picture?.
        /// </summary>
        internal static string ImageQuizDesc {
            get {
                return ResourceManager.GetString("ImageQuizDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match to picture.
        /// </summary>
        internal static string ImaqeQuizName {
            get {
                return ResourceManager.GetString("ImaqeQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, no. The correct answer is:.
        /// </summary>
        internal static string IncorrectAnswer {
            get {
                return ResourceManager.GetString("IncorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install english language in Windows settings..
        /// </summary>
        internal static string InstallEng {
            get {
                return ResourceManager.GetString("InstallEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning session finished..
        /// </summary>
        internal static string LearningFinished {
            get {
                return ResourceManager.GetString("LearningFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning streak.
        /// </summary>
        internal static string LearningStreak {
            get {
                return ResourceManager.GetString("LearningStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        internal static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need access to a microphone.
        /// </summary>
        internal static string MicrophoneNeeded {
            get {
                return ResourceManager.GetString("MicrophoneNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minigames.
        /// </summary>
        internal static string Minigames {
            get {
                return ResourceManager.GetString("Minigames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name:.
        /// </summary>
        internal static string NameEntry {
            get {
                return ResourceManager.GetString("NameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection is required..
        /// </summary>
        internal static string NetworkRequired {
            get {
                return ResourceManager.GetString("NetworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New collection.
        /// </summary>
        internal static string NewCollection {
            get {
                return ResourceManager.GetString("NewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next word.
        /// </summary>
        internal static string NextWord {
            get {
                return ResourceManager.GetString("NextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No achievements found..
        /// </summary>
        internal static string NoAchievements {
            get {
                return ResourceManager.GetString("NoAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No collections found..
        /// </summary>
        internal static string NoCollections {
            get {
                return ResourceManager.GetString("NoCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flashcards to learn.
        /// </summary>
        internal static string NoFlashcardsToLearn {
            get {
                return ResourceManager.GetString("NoFlashcardsToLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions.
        /// </summary>
        internal static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string NoResultsFoundText {
            get {
                return ResourceManager.GetString("NoResultsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source data for the word..
        /// </summary>
        internal static string NoSourceData {
            get {
                return ResourceManager.GetString("NoSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translation.
        /// </summary>
        internal static string NoTranslation {
            get {
                return ResourceManager.GetString("NoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No words in the database..
        /// </summary>
        internal static string NoWordsInDatabase {
            get {
                return ResourceManager.GetString("NoWordsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &apos;Online Speech Recognition&apos; in Windows settings..
        /// </summary>
        internal static string OnlineSpeech {
            get {
                return ResourceManager.GetString("OnlineSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must use 6 characters or more.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect!.
        /// </summary>
        internal static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording could not be played..
        /// </summary>
        internal static string PlaybackError {
            get {
                return ResourceManager.GetString("PlaybackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points earned:.
        /// </summary>
        internal static string PointsEarnedCount {
            get {
                return ResourceManager.GetString("PointsEarnedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred difficulty level.
        /// </summary>
        internal static string PreferredDifficulty {
            get {
                return ResourceManager.GetString("PreferredDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred lesson length.
        /// </summary>
        internal static string PreferredMaxLessonLength {
            get {
                return ResourceManager.GetString("PreferredMaxLessonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove collection.
        /// </summary>
        internal static string RemoveCollection {
            get {
                return ResourceManager.GetString("RemoveCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string RemoveCollectionDesc1 {
            get {
                return ResourceManager.GetString("RemoveCollectionDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and all the words in it?.
        /// </summary>
        internal static string RemoveCollectionDesc2 {
            get {
                return ResourceManager.GetString("RemoveCollectionDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to.
        /// </summary>
        internal static string SaveTo {
            get {
                return ResourceManager.GetString("SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a word to search.
        /// </summary>
        internal static string SearchEmpty {
            get {
                return ResourceManager.GetString("SearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or create a collection first..
        /// </summary>
        internal static string SelectCollectionError {
            get {
                return ResourceManager.GetString("SelectCollectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select collection.
        /// </summary>
        internal static string SelectCollectionPlaceholder {
            get {
                return ResourceManager.GetString("SelectCollectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence is generating....
        /// </summary>
        internal static string SentenceGenerating {
            get {
                return ResourceManager.GetString("SentenceGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange the words in the correct order.
        /// </summary>
        internal static string SentenceQuizDesc {
            get {
                return ResourceManager.GetString("SentenceQuizDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word order.
        /// </summary>
        internal static string SentenceQuizName {
            get {
                return ResourceManager.GetString("SentenceQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the sentence.
        /// </summary>
        internal static string SentenceRead {
            get {
                return ResourceManager.GetString("SentenceRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password incorrect.
        /// </summary>
        internal static string SignInError {
            get {
                return ResourceManager.GetString("SignInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Sign in.
        /// </summary>
        internal static string SignInPls {
            get {
                return ResourceManager.GetString("SignInPls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Sign in to continue.
        /// </summary>
        internal static string SignInWelcome {
            get {
                return ResourceManager.GetString("SignInWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an account? Sign up.
        /// </summary>
        internal static string SignUpPls {
            get {
                return ResourceManager.GetString("SignUpPls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking.
        /// </summary>
        internal static string SpeakingQuizName {
            get {
                return ResourceManager.GetString("SpeakingQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to flip.
        /// </summary>
        internal static string TapToFlip {
            get {
                return ResourceManager.GetString("TapToFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeNameDark {
            get {
                return ResourceManager.GetString("ThemeNameDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeNameLight {
            get {
                return ResourceManager.GetString("ThemeNameLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word is.
        /// </summary>
        internal static string TheWordIs {
            get {
                return ResourceManager.GetString("TheWordIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough words in the collection to make a quiz..
        /// </summary>
        internal static string TooLittleWords {
            get {
                return ResourceManager.GetString("TooLittleWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate before adding?.
        /// </summary>
        internal static string TranslateBeforeAdding {
            get {
                return ResourceManager.GetString("TranslateBeforeAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate sentence:.
        /// </summary>
        internal static string TranslateSentence {
            get {
                return ResourceManager.GetString("TranslateSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation API.
        /// </summary>
        internal static string TranslationApi {
            get {
                return ResourceManager.GetString("TranslationApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation error.
        /// </summary>
        internal static string TranslationError {
            get {
                return ResourceManager.GetString("TranslationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VICTORY.
        /// </summary>
        internal static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Linguibuddy,.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
